Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.synced_folder "../../Geometric-Modelling", "/Geometric-Modelling"

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '8192'
    vb.cpus = 2
	vb.gui = true
  end

  config.vm.provision :shell, path: "bootstrap.sh"
end